name: Lint Stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.0]
    steps:
    - uses: actions/checkout@v3
    - name: Front End Lint
      uses: actions/setup-node@v3
      with:
        working-directory: ./frontend
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx eslint . --ext .js,.jsx,.ts,.tsx

  backend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.0]
    steps:
    - uses: actions/checkout@v3
    - name: Back End Lint
      uses: actions/setup-node@v3
      with:
        working-directory: ./backend
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx eslint . --ext .js,.jsx,.ts,.tsx