name: Lint Stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.0]
    steps:

    - name: checkout repository
      uses: actions/checkout@v2
      
    - name: set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: install dependencies
      run: npm install
      working-directory: ./frontend

    - name: frontend Lint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
      working-directory: ./frontend


  backend-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.0]
    steps:

    - name: checkout repository
      uses: actions/checkout@v2
      
    - name: set up node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: install dependencies
      run: npm install
      working-directory: ./backend

    - name: backend Lint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
      working-directory: ./backend