# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Lint Stage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - run: cd ./frontend
    - uses: actions/checkout@v3
    - name: Eslint Checking
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npx eslint . --ext .js,.jsx,.ts,.tsx
    - run: cd ../backend
    - run: npx eslint . --ext .js,.jsx,.ts,.tsx
